name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkoutt
        uses: actions/checkout@v2
      - id: foo
        uses: nx-amiribenabdellah/unitTest-action@v1.6

  phplint-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: phplint with docker action
        uses: nx-amiribenabdellah/docker-action@v1.23

  phplint-composite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkoutt
        uses: actions/checkout@v3
      - name: phplint with composite action
        uses: nx-amiribenabdellah/phplint-composite@v1.7

  security-snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          composer require --dev phpunit/phpunit ^8
          php composer.phar update
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/php@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test

