name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

  php-build-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: php-build-action
        uses: nx-amiribenabdellah/php-build-action@2.18.0
        with:
          php-version: '8.1.1'
          tools: phpunit, phplint

  phpunit:
    needs: php-build-action
    runs-on: ubuntu-latest
    steps:
      - name: Checkoutt
        uses: actions/checkout@v2
      - name: php-build-action
        uses: nx-amiribenabdellah/php-build-action@2.18.0
        with:
          php-version: '8.1.1'
          tools: phpunit, phplint
      - uses: nx-amiribenabdellah/unitTest-action@v1.7

  phplint-docker:
    needs: php-build-action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: phplint with docker action
        uses: nx-amiribenabdellah/docker-action@v1.23

  phplint-composite:
    needs: php-build-action
    runs-on: ubuntu-latest
    steps:
      - name: Checkoutt
        uses: actions/checkout@v3
      - name: phplint with composite action
        uses: nx-amiribenabdellah/phplint-composite@v1.7

  security-snyk:
    needs: php-build-action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: php-build-action
        uses: nx-amiribenabdellah/php-build-action@2.18.0
        with:
          php-version: '8.1.1'
          tools: composer:v2, phpunit, phplint
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/php@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test

